import requests

response = requests.post("http://localhost:5000/call", json={
    "phone": "+18642072527",
    "message": """Hello... it's so nice to have you here...
I have a question for you...
Who’s gonna be brave enough...
to want me?
I think you could...
It’s very simple...
only two or three lines...
that’s all it takes...
to feel this connection...
Are you ready... to listen...
to follow... my voice...?

Gentle tapping
Can you hear that?
It’s the sound... of something... waiting...
waiting for you to come closer...
Just relax...
Let the moment sink in...
Let my words... pull you in...
Do you feel it?..."""})
print(response.json())